// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'constants/firebase_keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: webKey,
    appId: '1:598168443925:web:3e033de6b087d9e1ae021c',
    messagingSenderId: '598168443925',
    projectId: 'app-hackernews-api',
    authDomain: 'app-hackernews-api.firebaseapp.com',
    storageBucket: 'app-hackernews-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: androidKey,
    appId: '1:598168443925:android:05c7cd0067a0d10aae021c',
    messagingSenderId: '598168443925',
    projectId: 'app-hackernews-api',
    storageBucket: 'app-hackernews-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: appleKey,
    appId: '1:598168443925:ios:85cd8f1546f54d9aae021c',
    messagingSenderId: '598168443925',
    projectId: 'app-hackernews-api',
    storageBucket: 'app-hackernews-api.appspot.com',
    iosClientId:
        '598168443925-94av5db6cfmfg54p7pqq93guqiq6pp4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackernews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: appleKey,
    appId: '1:598168443925:ios:85cd8f1546f54d9aae021c',
    messagingSenderId: '598168443925',
    projectId: 'app-hackernews-api',
    storageBucket: 'app-hackernews-api.appspot.com',
    iosClientId:
        '598168443925-94av5db6cfmfg54p7pqq93guqiq6pp4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackernews',
  );
}
